### PR TITLE
Ft index

### PR DESCRIPTION
**Pull request by kbjude**
This is the very first PR on this project. The project is meant for a candidate to clone the News-week webpage for the candidates to to have an understanding if Bootstrap.
- I have used bootstrap grid for the layout
- The page is also responsive
- I used CSS and HTML five
- Used several bootstrap for the designing and styling

### CODE REVIEW

**Comment by SofiBretz** [comment]
'Code under review by SofiBretz. Thanks!✨'

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello! 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] Consider fixing the errors in both HTML files. You should have only 1 HTML file, please fix that.

errors


- [ ] Newsweek logo should be as the original page.




- [ ] 'Sign in' and 'subscribe' should be aligned as the original page to the right side, on the breakpoints also.



- [ ] Consider adding the 'search' icon as the original page.

- [ ] Align 'OPINION' as the original page.



- [ ] When 'scroll down', the center column has to move, and the other 2 external columns have to be static.



- [ ] 'SIGN UP FOR OUR NEWSLETTER' the logo is smaller and square, please follow the same design as the original page.




- [ ] 'IN THE MAGAZINE' and 'THE EDITOR'S PICK' in the original page have 4 columns, please follow the design as the original page, add the title with the logo also.




- [ ] 'FEATURED SLIDESHOWS' aligns the text with the images correctly, too much space between text and images, follow the original design page.

- [ ] 'U.S.' section and so on (World, Tech & Science...) align text and images exactly as the original page.

- [ ] 'SUBSCRIBE' align the content.



- [ ] Footer, align icons and make them bigger, follow the original design.




**Breakpoints to fix:**

- [ ] 'featured stories' and 'top story' has to be on the same line, look at the original page.



- [ ] 'Culture & travel' and 'More Stories' has to be aligned with the featured stories.



- [ ] 'Opinion', the text should be aligned to the left as the original page.




- [ ] 'Latest News', consider make the images smaller, as the original page. 



   Consider adding the text with black color.
   "Dershowitz Is Opening a Door to the Unthinkable
   BY PAUL GORDON" Consider to follow the text as the original page, "by..." isn't on this section.


- [ ] 'SIGN UP FOR OUR NEWSLETTER' section, should be center. The logo has to be with the same size. Consider follow the original page.




- [ ] 'IN THE MAGAZINE' it's supposed to be showing after the 'SIGN UP FOR OUR NEWSLETTER' section, please follow the correct order as the original page.




- [ ] This section "Saudi Arabia Accelerates Ahead..." It doesn't have to be here. does not follow the original structure of the page. Please move these two news with their corresponding section.




- [ ] 'SEE ALL FEATURES' It doesn't have to be here. does not follow the original structure of the page. Please move this two news with their corresponding section.

- [ ] 'IN THE MAGAZINE' in the original page have 4 columns, please follow the design as the original page, add the title with the logo also.




- [ ] 'THE EDITOR'S PICK' in the original page have 2 columns, please follow the design as the original page, add the title with the logo also.


- [ ] 'FEATURED SLIDESHOWS' in the original page has 3 columns, please follow the design as the original page, add the title with the logo also.




- [ ] 'U.S.' section and so on (World, Tech & Science...) consider style this exactly as the original page.
	This section 'share more' news: 3 columns, the last columns has 3 rows.




- [ ] 'SUBSCRIBE NEWSLETTER' section has to be exactly as the original page.



- [ ] 'Newsweek' footer should be exactly as the original page, social icons have to be on the right side also. Consider align the icons, date, and logo as the original page.



**Mobile breakpoint:**

- [ ] !!! Consider fixing **all** this breakpoint page exactly as the original page. 

[OPTIONAL]


_**After making the required changes please submit a new code review request**_
Good luck! 🍀 

SofiBretz.

**Comment by kbjude** [comment]
All feedback from the TSE implemented and requesting for another review before i merge

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi @kbjude, you have done a great job 👍 . We failed to fix some of the changes recommended by the previous reviewer 🙂 . Find comments below:
- Kindly fix the **HTML markup** as pointed out by the previous reviewer. We currently have 113 errors to fix. Below is the picture of some of the error messages
ck1
- Kindly follow the order described by the previous reviewer on a small screen. Check the order below:
  > 'Top stories' 'Featured stories' 'Opinion' 'More stories' 'Culture and Travel' 'Latest news' 'In the magazine'
Kindly follow this order or check [here](newsweek.com) for reference
- ```Culture and travel``` span 1 column on a small screen, currently, it spans 2 columns. Kindly fix it.7
Currently, this is how it looks
ct
```Original```
ct1

Kindly make these changes and submit another code review. 👍 
_Happy coding_ 👨‍💻 
@slack on Daniel Larbi Addo

**Comment by addod19** [comment]
Hi @kbjude, you left most of the comments by the first reviewer, Kindly go back and check our comments and try to fix it. Thank you

**Comment by kbjude** [comment]
I communicated to the last reviewer of my concern about  the feedback  that i had got from my first review and i let him know that from the time i started the project there has been a few changes on the original site and some of them are the things that the the first TSE asked me to change one of those is the order that  which is done by JS when i block JS i get to do a few things but not all. At this stage trying to change my order would require me to almost break my whole site. He advised me to go ahead with my implementation of the others requests and then make sure i write some thing like this when raising the next PR.

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi @kbjude, you did great fixing most of the comments 👍 nice work. The latest news section has disappeared on the medium screen. It only has ```the header```. Kindly check images below:
```Ours```
import
```Original```
import1

[OPTIONAL] comment
- Kindly increase the size of the social media icons 👍 

Kindly make these and submit another code review 👍 Congratulations, we are almost there.
@slack on **Daniel Larbi Addo**

**Comment by kbjude** [comment]
All feedback from the TSE implemented inclusive of the optional part.

**Review by MarioDena — APPROVED** [review]
## Congratulations on your project!

You implemented the requested changes so this project is approved.

Congratulations again !! 🎖 🏅 

## Code review by Mario Enrique Delgado Naranjo

**Pull request merged**
